[package]
name = "lightmotif-bench"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies.lightmotif]
path = "../lightmotif"
[dependencies]
typenum = "1.16"

[dev-dependencies]
bio = "1.1.0"

[[bench]]
name = "dna"
path = "dna.rs"
